// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD6qUZcVElR3bON1h7Rd0wzFmllEWsv9NM",
      authDomain: "smart-pill-care-18b09.firebaseapp.com",
      projectId: "smart-pill-care-18b09",
      storageBucket: "smart-pill-care-18b09.firebasestorage.app",
      messagingSenderId: "874339060230",
      appId: "1:874339060230:web:34e9ab4e4aa7e0e7a61187",
      measurementId: "G-J4VBZGQPJD",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsLyXJoxlOvhH0W1WKu0Wgqg2bXfqlCk',
    appId: '1:874339060230:android:3765909140eab993a61187',
    messagingSenderId: '874339060230',
    projectId: 'smart-pill-care-18b09',
    storageBucket: 'smart-pill-care-18b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6snh2P9FBuWkVZBxgPs2uu9BQoIddzo',
    appId: '1:874339060230:ios:c64b4529a110de1da61187',
    messagingSenderId: '874339060230',
    projectId: 'smart-pill-care-18b09',
    storageBucket: 'smart-pill-care-18b09.firebasestorage.app',
    iosBundleId: 'com.example.smartpillcare',
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6snh2P9FBuWkVZBxgPs2uu9BQoIddzo',
    appId: '1:874339060230:ios:c64b4529a110de1da61187',
    messagingSenderId: '874339060230',
    projectId: 'smart-pill-care-18b09',
    storageBucket: 'smart-pill-care-18b09.firebasestorage.app',
    iosBundleId: 'com.example.smartpillcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qUZcVELR3bON1h7Rd0wzFmllEWsv9NM',
    appId: '1:874339060230:web:63a668b2aceb402aa61187',
    messagingSenderId: '874339060230',
    projectId: 'smart-pill-care-18b09',
    authDomain: 'smart-pill-care-18b09.firebaseapp.com',
    storageBucket: 'smart-pill-care-18b09.firebasestorage.app',
    measurementId: 'G-Q0B50Z31E2',
  );
}