// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuXD_-4nMKlwPHl6jL4g8l6jDeXIVNh1E',
    appId: '1:687971242844:web:78c67c027f331f33ee6799',
    messagingSenderId: '687971242844',
    projectId: 'smart-pill-care',
    authDomain: 'smart-pill-care.firebaseapp.com',
    storageBucket: 'smart-pill-care.firebasestorage.app',
    measurementId: 'G-HS5YF7CM5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsLyXJoxlOvhH0W1WKu0Wgqg2bXfqlCk',
    appId: '1:874339060230:android:3765909140eab993a61187',
    messagingSenderId: '874339060230',
    projectId: 'smart-pill-care-18b09',
    storageBucket: 'smart-pill-care-18b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG90o5oJgP5lJAl5q-7N8qrtleW5NkPxM',
    appId: '1:687971242844:ios:64c3cab3ec0db2eeee6799',
    messagingSenderId: '687971242844',
    projectId: 'smart-pill-care',
    storageBucket: 'smart-pill-care.firebasestorage.app',
    iosBundleId: 'com.example.smartPillCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG90o5oJgP5lJAl5q-7N8qrtleW5NkPxM',
    appId: '1:687971242844:ios:64c3cab3ec0db2eeee6799',
    messagingSenderId: '687971242844',
    projectId: 'smart-pill-care',
    storageBucket: 'smart-pill-care.firebasestorage.app',
    iosBundleId: 'com.example.smartPillCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuXD_-4nMKlwPHl6jL4g8l6jDeXIVNh1E',
    appId: '1:687971242844:web:39af39fdd5412738ee6799',
    messagingSenderId: '687971242844',
    projectId: 'smart-pill-care',
    authDomain: 'smart-pill-care.firebaseapp.com',
    storageBucket: 'smart-pill-care.firebasestorage.app',
    measurementId: 'G-JZJJCK46DY',
  );
}
